### ISSUE TITLE
Good answer rejected

### ISSUE THREAD

**Issue by johnnygerard** [aleksei-berezkin/css-puzzler#25]
Answers B and C both render the same in Chrome.
Both answers are correct but the answer C was rejected (see screenshot below).

Answer B
```css
.a .a {
  background-color: #ffcdd2;
} 
div:last-child {
  background-color: #90caf9;
} 
```

Answer C
```css
.c>.a {
  background-color: #ffcdd2;
} 
.a {
  background-color: #90caf9;
} 
```

HTML
```html
<div class="a">
  a 
  <div class="c">
    c 
    <div class="a">a</div>
    <div class="a">a</div>
    <div class="d">d</div>
    <div class="b">b</div>
  </div>
</div>
```

Shared CSS
```css
div {
  display: inline-block;
  padding: .5em;
  border: 1px solid #000;
} 
body {
  color: #000;
  font-family: Menlo,
    "Ubuntu Mono", Consolas,
    source-code-pro, monospace;
  font-size: 13px;
} 
```

![image](https://user-images.githubusercontent.com/57420910/213942889-7f6b3b04-859f-49a5-9b0b-e24938ee3f5a.png)
